Feature backoffice forms
Toka69/P5_PHP-blog pull request #15
Opened 2020-11-25 07:47 UTC by Toka69

Hello.

I added the edit pages for users, comments and posts. The processing of the form after editing is in progress.

Thanks for the review.

2020-11-25 09:53 UTC, TBoileau requested changes
Ajouter la fonction "path" à Twig

2020-11-25 09:53 UTC, TBoileau commented on src/Controller/BackofficeController.php
> +        }
```php
$user = $this->userManager->find($_GET["id"]);
$errors = [];
if ($_SERVER ["REQUEST_METHOD"] == "POST") {
    if (!isset($_POST["first_name"]) || is_empty($_POST["first_name"])) {
         $errors["first_name"] = "Veuillez saisir votre prénom.";
    }

    if (count($errors) === 0) {
        $user->setFirstName($_POST["first_name"]);
        $this->userManager->update($user);
        return $this->redirect("backofficeUsers");
    }
}
return $this->render("user/edit.html.twig", ["user" => $user, "errors" => $errors]);
```

2020-11-25 09:53 UTC, TBoileau commented on src/Controller/SecurityController.php
>                      }
```php
$errors = [];
if (!filter_var($securForm['email'], FILTER_VALIDATE_EMAIL)) {
    $errors[] = "";
}
if (!preg_match("#.*^(?=.{8,20})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).*$#", $securForm['password'])) {
    $errors[] = "";
}
$request = $manager->checkCredentials($securForm['email']);
if ($request) {
    $errors[] = "";
}
if ($securForm['password'] !== $securForm['repeatPassword']) {
    $errors[] = "";
}

if (count($error) === 0) {
     $user = new User(...);
     $this->userManager->add($user);
     $_SESSION["MESSAGE"] = "Effectué";
     $this->redirect("...");
}

return $this->render("...", ["errors" => $errors]);
```

2020-12-02 07:25 UTC, Toka69 commented on src/Controller/BackofficeController.php
> +        }
J'ai laissé finalement le retour à la méthode qui génère la page. Donc plus besoin de la méthode path.

2020-12-02 09:50 UTC, TBoileau requested changes
Attention à la gestion des erreurs en traitement de form (voir CommentController)

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +            $errors = [];
remonter en dehors du if

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +            ]);
supprimer

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +            ]);
ajouter "errors"

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +        return $this->redirect("backofficeComments");
pas besoin de redirection si bad request (id inexistant)

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +            $comment = $this->commentsManager->getComment($_GET["id"]);
à remonter en dehors du if, et si le commentaire n'existe pas, balancer une 400 (bad request) => throw new InvalidArgumentException

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/HomeController.php
> +
Ajouter la méthode "badRequest" dans le cas d'une erreur 400

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +        if (!isset($_SESSION["user"])){return $this->redirect("login");}
balancer une erreur 401

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/CommentsController.php
> +        if (!isset($_SESSION["user"])){return $this->redirect("login");}
si pas authentifier => 401, si connecté mais pas admin => 403

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/PostsController.php
> +        return $this->redirect("backofficePosts");
Reprendre CommentController

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/SecurityController.php
>                  ]);
Faire une redirection, et pour gérer tes messages de confirmation, gérer en SESSION

2020-12-02 09:50 UTC, TBoileau commented on src/Controller/SecurityController.php
>                      "message" => 'Ce compte email n\'existe pas! Veuillez réesayer.'
eviter de préciser que l'email n'existe pas, renvoie toujours un message disant que tu as envoyé l'email, ou pas, c'est arbitraire, on privilégie la sécurité ou l'UX

2020-12-02 09:50 UTC, TBoileau commented on templates/backofficeComments.html.twig
> +                            <tr class="clickable-table-row" onclick="location.href='back-read-comment?id={{ comment.id }}'">
Eviter le onclick

2020-12-02 09:50 UTC, TBoileau commented on templates/backofficePost.html.twig
> +    </div>
attention à l'indentation

2020-12-02 09:50 UTC, TBoileau commented on templates/backofficePosts.html.twig
> +                        <tr class="clickable-table-row" onclick="location.href='back-read-post?id={{ post.id }}'">
pas de onlick

2020-12-06 13:21 UTC, merged